---
deployment:
  tasks:
    - export DEPLOYPATH=/home/charle22/public_html/tools.veerl.es/apps/loginveerles/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .env.production $DEPLOYPATH/apps/auth/.env.example.production
    - /bin/cp .gitignore $DEPLOYPATH/
